### ISSUE TITLE
Irish, Chinese, South Korean addresses don’t validate

### ISSUE THREAD

**Issue by MacLake** [mirumee/google-i18n-address#24]
Whatever I enter in the county field of an Irish address, it won’t validate, even all variations of Limerick from the [list of counties on Wikipedia](https://en.wikipedia.org/wiki/Counties_of_Ireland). If there’s a check of the county name, it should be a drop down menu anyway. On the other hand I can enter any nonsense on the postal code field without getting a validation error.

**Comment by patrys** [comment]
I see that all county names provided by Google's address services are prefixed with "Co." which is likely the cause of your problem. Are you using Saleor by any chance? I am asking because this library does not display forms of its own and Saleor should indeed offer a way to choose from a list of valid choices.

**Comment by MacLake** [comment]
Yes, I use Saleor. Maybe it’s an issue of Saleor. The thing is that Saleor displays a text input field and no dropdown choice widget. for county on Irish forms.

**Comment by patrys** [comment]
Right, we'll solve it at the Saleor level then. As to whether Irish counties make sense or not, the data is maintained as part of the following Google project: https://github.com/googlei18n/libaddressinput

Currently it lists the following counties:
* Co. Carlow
* Co. Cavan
* Co. Clare
* Co. Cork
* Co. Donegal
* Co. Dublin
* Co. Galway
* Co. Kerry
* Co. Kildare
* Co. Kilkenny
* Co. Laois
* Co. Leitrim
* Co. Limerick
* Co. Longford
* Co. Louth
* Co. Mayo
* Co. Meath
* Co. Monaghan
* Co. Offaly
* Co. Roscommon
* Co. Sligo
* Co. Tipperary
* Co. Waterford
* Co. Westmeath
* Co. Wexford
* Co. Wicklow

**Comment by MacLake** [comment]
Hi again, we still have this issue, and also customers from China and South Korea can’t order in our shop because the address form complains when they enter their address.
The idea of having flexible address models is great, but when customers can’t submit their orders, it’s not so great. ;-)

I’d also be happy to fix it and contribute back to the project if you give me a hint.
In this package I find mainly JSON data and __init__.py and downloader.py. Where is it decided whether a field becomes a normal text field or a choice field? Maybe in _make_choices(rules, translated=False)?

**Comment by acm4b** [comment]
<img width="1380" alt="Screen Shot 2019-09-30 at 3 13 47 PM" src="https://user-images.githubusercontent.com/54292858/65913117-ee0cec00-e394-11e9-810d-f7fe09a319b5.png">

To follow up on this. Why is `postal_code_matchers` empty when calling `get_validation_rules` but a regex is available when calling `load_validation_data`?
