### ISSUE TITLE
"%" in README.rst enters spec file unescaped

### ISSUE THREAD

**Issue by orange-kao** [mirumee/google-i18n-address#53]
## Reproduce steps
```
cd $HOME
rm -fR builddir
mkdir builddir
cd builddir
mkdir rpmbuild

git clone git://github.com/mirumee/google-i18n-address.git
cd google-i18n-address

./setup.py bdist_rpm --spec-only
git archive --output $HOME/builddir/rpmbuild/google-i18n-address-2.4.0.tar.gz --prefix google-i18n-address-2.4.0/ HEAD
rpmbuild -bb $PWD/dist/google-i18n-address.spec --define "_topdir $HOME/builddir/rpmbuild" --define "_sourcedir $HOME/builddir/rpmbuild" --nodebuginfo
```

## Result on Fedora 31 (rpmbuild 4.15.1)
Running `rpm -qip` on generated RPM under `builddir/rpmbuild/RPMS/noarch` reveals that `%S` from README.rst became `%SOURCE` in package description.

## Result on Fedora 33 beta (rpmbuild 4.16.0)
Build failure on `rpmbuild` 
```
line 226: %S: argument expected
```

## Proposal
Pull request #52 fix the issue by replacing `%` with `%%` from README.rst.

**Comment by patrys** [comment]
Are you sure it's not the `.spec` file that needs to be fixed? It seems that it blindly includes the description returned by Python assuming that it's safe and won't expand any macros.

**Comment by orange-kao** [comment]
Thank you. I agree and it seems to be a `setuptools` related bug. The content of `long_description` became part of spec file unescaped. I'll report the bug to them.
