### ISSUE TITLE
Bogus sorting codes for French territories

### ISSUE THREAD

**Issue by jrlevine** [mirumee/google-i18n-address#58]
The formats for PM YT MC WF NC MF GP GF MQ BL RE all erroneously include a %X sorting code.

They are all part of France, or for Monaco, a statelet whose post office is run by France. Both the French La Poste web site and the UPU confirm that they use standard French addresses with the five digit postal code before the city, no sorting code. For example, for PM https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/spmEn.pdf

It may have been confusing that for each territory the first three digits of its French code are fixed and only the last two vary within the territory, which might have been misinterpreted as a sorting code.

**Comment by patrys** [comment]
@jrlevine We are packaging data provided and maintained by Google, please raise that issue with the Chromium i18n team.
