### ISSUE TITLE
Validating postal addresses

### ISSUE THREAD

**Issue by Jimchoo91** [mirumee/google-i18n-address#64]
Hi, I had a question about this library. It is possible to validate a postal address without being able to provide all of the rest of the information? For example, let’s say I am able to provide the country and region but nothing else, or I am I only able to provide the country and street?

thanks

**Comment by artursmet** [comment]
Hi @Jimchoo91, 
It depends on the country in general, however the vast majority of country validation rules I have seen, is about validating the format of the postal codes. Each country has a dedicated formatting rules for the postcodes, additionally some of the countries require administrative area code to be provided, like state in the USA.

This library is not able to validate addresses on street level.
