### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by brylie-wolt** [mirumee/google-i18n-address#72]
The README contains a badge that says "build failing, " leading to a Circle CI page with the following error.

> No .circleci/config.yml was found in your project. Add a configuration file to your repository or refer to [documentation](https://circleci.com/docs/2.0/configuration-reference/).

It would be good to update the Circle CI configuration or remove the badge to avoid confusion.

**Comment by rafalp** [comment]
Fixed on main branch
